/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunRouteImport } from './routes/run'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as JenkinsRouteImport } from './routes/jenkins'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsQualityRouteImport } from './routes/reports.quality'
import { Route as ReportsBusinessRouteImport } from './routes/reports.business'
import { Route as AuditTradesRouteImport } from './routes/audit.trades'
import { Route as AuditPipelineRouteImport } from './routes/audit.pipeline'
import { Route as AuditAccessRouteImport } from './routes/audit.access'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const JenkinsRoute = JenkinsRouteImport.update({
  id: '/jenkins',
  path: '/jenkins',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsQualityRoute = ReportsQualityRouteImport.update({
  id: '/reports/quality',
  path: '/reports/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsBusinessRoute = ReportsBusinessRouteImport.update({
  id: '/reports/business',
  path: '/reports/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTradesRoute = AuditTradesRouteImport.update({
  id: '/audit/trades',
  path: '/audit/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditPipelineRoute = AuditPipelineRouteImport.update({
  id: '/audit/pipeline',
  path: '/audit/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditAccessRoute = AuditAccessRouteImport.update({
  id: '/audit/access',
  path: '/audit/access',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jenkins': typeof JenkinsRoute
  '/rules': typeof RulesRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/audit/access': typeof AuditAccessRoute
  '/audit/pipeline': typeof AuditPipelineRoute
  '/audit/trades': typeof AuditTradesRoute
  '/reports/business': typeof ReportsBusinessRoute
  '/reports/quality': typeof ReportsQualityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jenkins': typeof JenkinsRoute
  '/rules': typeof RulesRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/audit/access': typeof AuditAccessRoute
  '/audit/pipeline': typeof AuditPipelineRoute
  '/audit/trades': typeof AuditTradesRoute
  '/reports/business': typeof ReportsBusinessRoute
  '/reports/quality': typeof ReportsQualityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jenkins': typeof JenkinsRoute
  '/rules': typeof RulesRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/audit/access': typeof AuditAccessRoute
  '/audit/pipeline': typeof AuditPipelineRoute
  '/audit/trades': typeof AuditTradesRoute
  '/reports/business': typeof ReportsBusinessRoute
  '/reports/quality': typeof ReportsQualityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/jenkins'
    | '/rules'
    | '/run'
    | '/settings'
    | '/sources'
    | '/audit/access'
    | '/audit/pipeline'
    | '/audit/trades'
    | '/reports/business'
    | '/reports/quality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/jenkins'
    | '/rules'
    | '/run'
    | '/settings'
    | '/sources'
    | '/audit/access'
    | '/audit/pipeline'
    | '/audit/trades'
    | '/reports/business'
    | '/reports/quality'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/jenkins'
    | '/rules'
    | '/run'
    | '/settings'
    | '/sources'
    | '/audit/access'
    | '/audit/pipeline'
    | '/audit/trades'
    | '/reports/business'
    | '/reports/quality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  JenkinsRoute: typeof JenkinsRoute
  RulesRoute: typeof RulesRoute
  RunRoute: typeof RunRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  AuditAccessRoute: typeof AuditAccessRoute
  AuditPipelineRoute: typeof AuditPipelineRoute
  AuditTradesRoute: typeof AuditTradesRoute
  ReportsBusinessRoute: typeof ReportsBusinessRoute
  ReportsQualityRoute: typeof ReportsQualityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jenkins': {
      id: '/jenkins'
      path: '/jenkins'
      fullPath: '/jenkins'
      preLoaderRoute: typeof JenkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/quality': {
      id: '/reports/quality'
      path: '/reports/quality'
      fullPath: '/reports/quality'
      preLoaderRoute: typeof ReportsQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/business': {
      id: '/reports/business'
      path: '/reports/business'
      fullPath: '/reports/business'
      preLoaderRoute: typeof ReportsBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/trades': {
      id: '/audit/trades'
      path: '/audit/trades'
      fullPath: '/audit/trades'
      preLoaderRoute: typeof AuditTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/pipeline': {
      id: '/audit/pipeline'
      path: '/audit/pipeline'
      fullPath: '/audit/pipeline'
      preLoaderRoute: typeof AuditPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/access': {
      id: '/audit/access'
      path: '/audit/access'
      fullPath: '/audit/access'
      preLoaderRoute: typeof AuditAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  JenkinsRoute: JenkinsRoute,
  RulesRoute: RulesRoute,
  RunRoute: RunRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  AuditAccessRoute: AuditAccessRoute,
  AuditPipelineRoute: AuditPipelineRoute,
  AuditTradesRoute: AuditTradesRoute,
  ReportsBusinessRoute: ReportsBusinessRoute,
  ReportsQualityRoute: ReportsQualityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
